### ISSUE TITLE
Give proper credits!

### ISSUE THREAD

**Issue by Pablito2020** [SamarV-121/android_device_google_sprout#1]
I know that you used some commits from my device tree... It doesn't make me angry but please give credits! ;)
Cheers!
Pablito2020

**Comment by SamarV-121** [comment]
oops -,- KK 
but which commits ? that mtk's powerHAL ? i firstly saw that on ur git but u made some changes.so that hal didnt worked properly so i simply used from xen0n's arale trees :)

**Comment by Pablito2020** [comment]
the mtk powerhal the sdcardfs commit, and maybe some more
